package httpapi

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"image"
	"image/color"
	"image/png"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/auucoder/gptgrok2api-go/internal/provider"
)

func TestGPTImageSyncResponseProtocol(t *testing.T) {
	for _, mode := range []string{"generations", "edits-json", "edits-multipart"} {
		t.Run(mode, func(t *testing.T) {
			s := imageTaskTestServer(t)
			if _, _, _, err := s.store.AddAccounts(nil, []map[string]any{{"access_token": "jwt.header.payload", "pool": "basic"}}); err != nil {
				t.Fatal(err)
			}
			output := image.NewRGBA(image.Rect(0, 0, 2, 2))
			output.Set(1, 1, color.RGBA{R: 255, A: 255})
			var generated bytes.Buffer
			if err := png.Encode(&generated, output); err != nil {
				t.Fatal(err)
			}
			fileID := "file_000000001234567890abcdef12345678"
			var upstream *httptest.Server
			upstream = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				switch r.URL.Path {
				case "/":
					io.WriteString(w, `<html data-build="test-build"></html>`)
				case "/backend-api/files":
					writeJSON(w, 200, map[string]any{"file_id": "file_reference", "upload_url": upstream.URL + "/upload"})
				case "/upload":
					data, _ := io.ReadAll(r.Body)
					if !bytes.Equal(data, tinyPNG) {
						t.Error("reference changed")
					}
					w.WriteHeader(201)
				case "/backend-api/files/file_reference/uploaded":
					writeJSON(w, 200, map[string]any{"status": "success"})
				case "/backend-api/sentinel/chat-requirements/prepare":
					writeJSON(w, 200, map[string]any{"prepare_token": "test"})
				case "/backend-api/sentinel/chat-requirements/finalize":
					writeJSON(w, 200, map[string]any{"token": "test"})
				case "/backend-api/f/conversation/prepare":
					writeJSON(w, 200, map[string]any{"conduit_token": "test"})
				case "/backend-api/f/conversation":
					w.Header().Set("Content-Type", "text/event-stream")
					io.WriteString(w, `data: {"conversation_id":"conversation-1","message":{"content":{"parts":["file-service://`+fileID+`"]}}}`+"\n\ndata: [DONE]\n\n")
				case "/backend-api/conversation/conversation-1":
					writeHTTPAPIGeneratedImageConversation(w, fileID)
				case "/backend-api/files/" + fileID + "/download":
					writeJSON(w, 200, map[string]any{"download_url": upstream.URL + "/blob"})
				case "/blob":
					w.Header().Set("Content-Type", "image/png")
					w.Write(generated.Bytes())
				default:
					http.NotFound(w, r)
				}
			}))
			defer upstream.Close()
			s.openAIImage = provider.NewOpenAIImage(upstream.URL, upstream.Client(), nil, 30*time.Second)
			var req *http.Request
			if mode == "edits-multipart" {
				var body bytes.Buffer
				writer := multipart.NewWriter(&body)
				writer.WriteField("model", "gpt-image-2")
				writer.WriteField("prompt", "a red cat")
				part, err := writer.CreateFormFile("image[]", "reference.png")
				if err != nil {
					t.Fatal(err)
				}
				part.Write(tinyPNG)
				writer.Close()
				req = httptest.NewRequest("POST", "/v1/images/edits", &body)
				req.Header.Set("Content-Type", writer.FormDataContentType())
			} else {
				body := `{"model":"gpt-image-2","prompt":"a red cat"}`
				path := "/v1/images/generations"
				if mode == "edits-json" {
					path = "/v1/images/edits"
					body = strings.TrimSuffix(body, "}") + `,"images":["data:image/png;base64,` + base64.StdEncoding.EncodeToString(tinyPNG) + `"]}`
				}
				req = httptest.NewRequest("POST", path, strings.NewReader(body))
				req.Header.Set("Content-Type", "application/json")
			}
			req.Header.Set("Authorization", "Bearer api-secret")
			w := httptest.NewRecorder()
			s.Handler().ServeHTTP(w, req)
			if w.Code != 200 {
				t.Fatalf("response: %d %s", w.Code, w.Body.String())
			}
			var result struct {
				Created int64               `json:"created"`
				Data    []map[string]string `json:"data"`
				Usage   any                 `json:"usage"`
			}
			if err := json.Unmarshal(w.Body.Bytes(), &result); err != nil {
				t.Fatal(err)
			}
			if result.Created <= 0 || len(result.Data) != 1 || result.Usage != nil {
				t.Fatal("invalid response metadata")
			}
			raw, err := base64.StdEncoding.DecodeString(result.Data[0]["b64_json"])
			if err != nil || !bytes.Equal(raw, generated.Bytes()) || len(result.Data[0]) != 1 {
				t.Fatal("expected only generated Base64 image")
			}
		})
	}
}

func TestGPTImageRejectsLegacyResponseFormatBeforeGeneration(t *testing.T) {
	for _, mode := range []string{"generations", "edits"} {
		for _, format := range []string{"url", "b64_json", "invalid"} {
			t.Run(mode+"/"+format, func(t *testing.T) {
				s := imageTaskTestServer(t) // No account: validation must precede any upstream attempt.
				body := map[string]any{"model": "gpt-image-2", "prompt": "cat", "response_format": format}
				if mode == "edits" {
					body["images"] = []string{"data:image/png;base64," + base64.StdEncoding.EncodeToString(tinyPNG)}
				}
				raw, _ := json.Marshal(body)
				w := imageTaskCall(s, "POST", "/v1/images/"+mode, "api-secret", string(raw))
				if w.Code != 400 || !strings.Contains(w.Body.String(), `"param":"response_format"`) || !strings.Contains(w.Body.String(), `"type":"invalid_request_error"`) {
					t.Fatalf("response: %d %s", w.Code, w.Body.String())
				}
			})
		}
	}
}
