package httpapi

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"image"
	"image/color"
	"image/png"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/auucoder/gptgrok2api-go/internal/provider"
)

func imageTaskTestServer(t *testing.T) *Server {
	t.Helper()
	root := t.TempDir()
	cfg := testConfig()
	cfg.RootDir, cfg.DataDir = root, root
	cfg.ConfigPath = filepath.Join(root, "config.json")
	cfg.AccountsPath = filepath.Join(root, "accounts.json")
	cfg.AuthKeysPath = filepath.Join(root, "auth_keys.json")
	cfg.ImageDataDir = filepath.Join(root, "images")
	cfg.QueuePath = filepath.Join(root, "queue.json")
	cfg.RequestTimeout = 30 * time.Second
	return New(cfg)
}

func imageTaskCall(s *Server, method, path, key, body string) *httptest.ResponseRecorder {
	r := httptest.NewRequest(method, path, strings.NewReader(body))
	r.Header.Set("Authorization", "Bearer "+key)
	r.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	s.Handler().ServeHTTP(w, r)
	return w
}

func TestImageTaskAsyncLifecycleSurvivesCallerCancellation(t *testing.T) {
	for _, tc := range []struct {
		name, mode      string
		busyDownloads   int
		wantError       bool
		upstreamFailure string
	}{
		{"generate", "generations", 0, false, ""}, {"edit", "edits", 0, false, ""},
		{"storage-busy-recover", "edits", 1, false, ""}, {"storage-busy-fail", "edits", 3, true, ""},
		{"terminal-stream-error", "generations", 0, true, "stream"},
		{"terminal-poll-error", "edits", 0, true, "poll"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			mode := tc.mode
			var generateCalls, downloadCalls, metadataCalls, pollCalls atomic.Int32
			const rejection = "生成的图片可能违反了关于潜在欺诈或诈骗活动的防护限制。"
			failedMessage := map[string]any{"author": map[string]any{"role": "assistant"}, "status": "finished_successfully", "end_turn": true, "metadata": map[string]any{"is_error": true}, "content": map[string]any{"content_type": "text", "parts": []any{rejection}}}
			s := imageTaskTestServer(t)
			s.cfg.ChatMaxRetries = 2
			s.cfg.ChatRetryCodes = map[int]bool{502: true, 422: true, 504: true}
			if _, _, _, err := s.store.AddAccounts(nil, []map[string]any{{"access_token": "jwt.header.payload", "email": "async@example.test", "pool": "basic"}}); err != nil {
				t.Fatal(err)
			}
			started, release := make(chan struct{}), make(chan struct{})
			defer func() {
				select {
				case <-release:
				default:
					close(release)
				}
			}()
			fileID := "file_000000001234567890abcdef12345678"
			output := image.NewRGBA(image.Rect(0, 0, 2, 2))
			output.Set(1, 1, color.RGBA{R: 255, A: 255})
			var generated bytes.Buffer
			if err := png.Encode(&generated, output); err != nil {
				t.Fatal(err)
			}
			var upstream *httptest.Server
			upstream = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				switch r.URL.Path {
				case "/backend-api/files":
					writeJSON(w, 200, map[string]any{"file_id": "file_reference", "upload_url": upstream.URL + "/reference-upload"})
				case "/reference-upload":
					raw, _ := io.ReadAll(r.Body)
					if !bytes.Equal(raw, tinyPNG) {
						t.Error("reference bytes did not reach upstream")
					}
					w.WriteHeader(201)
				case "/backend-api/files/file_reference/uploaded":
					writeJSON(w, 200, map[string]any{"status": "success"})
				case "/":
					_, _ = w.Write([]byte(`<html data-build="test-build"></html>`))
				case "/backend-api/sentinel/chat-requirements/prepare":
					writeJSON(w, 200, map[string]any{"prepare_token": "test"})
				case "/backend-api/sentinel/chat-requirements/finalize":
					writeJSON(w, 200, map[string]any{"token": "test"})
				case "/backend-api/f/conversation/prepare":
					writeJSON(w, 200, map[string]any{"conduit_token": "test"})
				case "/backend-api/f/conversation":
					if mode == "edits" {
						raw, _ := io.ReadAll(r.Body)
						if !bytes.Contains(raw, []byte("file_reference")) {
							t.Error("edit conversation missing reference")
						}
					}
					if generateCalls.Add(1) == 1 {
						close(started)
					} else {
						t.Error("download failure retriggered image generation")
					}
					select {
					case <-release:
					case <-r.Context().Done():
						return
					}
					w.Header().Set("Content-Type", "text/event-stream")
					if tc.upstreamFailure == "stream" {
						raw, _ := json.Marshal(map[string]any{"conversation_id": "conversation-1", "message": failedMessage})
						_, _ = w.Write(append(append([]byte("data: "), raw...), []byte("\n\ndata: [DONE]\n\n")...))
						return
					}
					_, _ = w.Write([]byte("data: {\"conversation_id\":\"conversation-1\",\"message\":{\"content\":{\"parts\":[\"file-service://" + fileID + "\"]}}}\n\ndata: [DONE]\n\n"))
				case "/backend-api/conversation/conversation-1":
					pollCalls.Add(1)
					if tc.upstreamFailure == "poll" {
						writeJSON(w, 200, map[string]any{"mapping": map[string]any{"final": map[string]any{"message": failedMessage}}})
						return
					}
					writeHTTPAPIGeneratedImageConversation(w, fileID)
				case "/backend-api/files/" + fileID + "/download":
					metadataCalls.Add(1)
					writeJSON(w, 200, map[string]any{"download_url": upstream.URL + "/blob"})
				case "/blob":
					w.Header().Set("Content-Type", "image/png")
					if downloadCalls.Add(1) <= int32(tc.busyDownloads) {
						_, _ = w.Write([]byte("\xef\xbb\xbf<?xml version=\"1.0\"?><Error><Code>ServerBusy</Code></Error>"))
					} else {
						_, _ = w.Write(generated.Bytes())
					}
				default:
					http.NotFound(w, r)
				}
			}))
			defer func() {
				select {
				case <-release:
				default:
					close(release)
				}
				upstream.Close()
			}()
			s.openAIImage = provider.NewOpenAIImage(upstream.URL, upstream.Client(), nil, 30*time.Second)
			body := `{"client_task_id":"async-one","model":"gpt-image-2","prompt":"a cat","n":1}`
			if mode == "edits" {
				body = strings.TrimSuffix(body, "}") + `,"images":["data:image/png;base64,` + base64.StdEncoding.EncodeToString(tinyPNG) + `"]}`
			}
			ctx, cancel := context.WithCancel(context.Background())
			r := httptest.NewRequest(http.MethodPost, "/api/image-tasks/"+mode, strings.NewReader(body)).WithContext(ctx)
			r.Header.Set("Authorization", "Bearer api-secret")
			r.Header.Set("Content-Type", "application/json")
			w := httptest.NewRecorder()
			s.Handler().ServeHTTP(w, r)
			cancel()
			if w.Code != 202 {
				t.Fatalf("submit: %d %s", w.Code, w.Body.String())
			}
			select {
			case <-started:
			case <-time.After(5 * time.Second):
				t.Fatalf("background generation did not start: %s", imageTaskCall(s, "GET", "/api/image-tasks/async-one", "api-secret", "").Body.String())
			}
			for i := 0; i < 5; i++ {
				w = imageTaskCall(s, "POST", "/api/image-tasks/"+mode, "api-secret", body)
				if w.Code != 202 {
					t.Fatalf("idempotent submission: %d", w.Code)
				}
				w = imageTaskCall(s, "GET", "/api/image-tasks/async-one", "api-secret", "")
				if !strings.Contains(w.Body.String(), `"status":"running"`) {
					t.Fatal(w.Body.String())
				}
			}
			w = imageTaskCall(s, "POST", "/api/image-tasks/"+mode, "api-secret", strings.Replace(body, "a cat", "a dog", 1))
			if w.Code != 409 {
				t.Fatalf("conflicting duplicate: %d", w.Code)
			}
			w = imageTaskCall(s, "GET", "/api/image-tasks/async-one", "admin-secret", "")
			if w.Code != 404 {
				t.Fatalf("cross-owner read: %d", w.Code)
			}
			close(release)
			deadline := time.After(5 * time.Second)
			for {
				w = imageTaskCall(s, "GET", "/api/image-tasks/async-one", "api-secret", "")
				var task imageTaskState
				if err := json.Unmarshal(w.Body.Bytes(), &task); err != nil {
					t.Fatal(err)
				}
				if task.Status == "error" {
					wantReason := "ServerBusy"
					if tc.upstreamFailure != "" {
						wantReason = rejection
					}
					if !tc.wantError || !strings.Contains(task.Error, wantReason) {
						t.Fatal(task.Error)
					}
					if len(task.Data) != 0 {
						t.Fatal("failed download returned image URLs")
					}
					break
				}
				if task.Status == "success" {
					if tc.wantError {
						t.Fatal("storage error counted as successful image")
					}
					if len(task.Data) != 1 || task.Data[0]["url"] == "" || task.Data[0]["b64_json"] != nil {
						t.Fatalf("missing result: %s", w.Body.String())
					}
					break
				}
				select {
				case <-deadline:
					t.Fatal("task did not finish")
				case <-time.After(10 * time.Millisecond):
				}
			}
			// A new process can query the completed result, and the same request never reruns.
			reloaded := New(s.cfg)
			w = imageTaskCall(reloaded, "POST", "/api/image-tasks/"+mode, "api-secret", body)
			expectedStatus, logStatus := "success", "success"
			if tc.wantError {
				expectedStatus, logStatus = "error", "failed"
			}
			if w.Code != 202 || !strings.Contains(w.Body.String(), `"status":"`+expectedStatus+`"`) {
				t.Fatal(w.Body.String())
			}
			// The worker writes one completed call; acknowledgement, polling, retries
			// and querying after a process restart must not create extra call records.
			assertImageTaskCallLog(t, reloaded, "async-one", logStatus, "/v1/images/"+mode)
			expectedDownloads := tc.busyDownloads + 1
			if tc.wantError {
				expectedDownloads = 3
			}
			if tc.upstreamFailure != "" {
				expectedDownloads = 0
				wantPolls := int32(1)
				if tc.upstreamFailure == "stream" {
					wantPolls = 0
				}
				if pollCalls.Load() != wantPolls {
					t.Fatalf("terminal failure kept polling: %d", pollCalls.Load())
				}
			}
			if generateCalls.Load() != 1 || int(downloadCalls.Load()) != expectedDownloads || metadataCalls.Load() != downloadCalls.Load() {
				t.Fatalf("generation/download/metadata counts: %d/%d/%d", generateCalls.Load(), downloadCalls.Load(), metadataCalls.Load())
			}
			if tc.wantError {
				entries, _ := os.ReadDir(s.cfg.ImageDataDir)
				if len(entries) != 0 {
					t.Fatal("error file was persisted")
				}
			}

		})
	}
}

func TestImageTaskPersistenceAndOwnerIsolation(t *testing.T) {
	s := imageTaskTestServer(t)
	for _, status := range []string{"queued", "running", "success", "error"} {
		task := &imageTaskState{ID: "same-id", OwnerID: status, Status: status, Prompt: "private prompt", Images: [][]byte{[]byte("private input")}, RequestHash: "digest", CreatedAt: time.Now().UTC().Format(time.RFC3339)}
		if err := s.saveImageTaskLocked(task); err != nil {
			t.Fatal(err)
		}
		path := filepath.Join(s.imageTasksDir(), imageTaskKey(status, task.ID)+".json")
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if strings.Contains(string(raw), "private") {
			t.Fatal("persisted private input")
		}
		info, err := os.Stat(path)
		if err != nil || info.Mode().Perm() != 0o600 {
			t.Fatalf("unsafe task file: %v", err)
		}
	}
	reloaded := New(s.cfg)
	if len(reloaded.imageTasks) != 4 {
		t.Fatal("owners replaced each other's task")
	}
	for _, status := range []string{"queued", "running", "success", "error"} {
		task := reloaded.imageTasks[imageTaskKey(status, "same-id")]
		if status == "queued" || status == "running" {
			if task.Status != "error" || !strings.Contains(task.Error, "restarted") {
				t.Fatalf("interrupted task: %+v", task)
			}
		} else if task.Status != status {
			t.Fatalf("terminal result changed: %+v", task)
		}
	}
	// Storage failure must reject the request before any upstream work starts.
	blocked := imageTaskTestServer(t)
	if err := os.WriteFile(blocked.imageTasksDir(), []byte("not a directory"), 0o600); err != nil {
		t.Fatal(err)
	}
	w := imageTaskCall(blocked, "POST", "/api/image-tasks/generations", "api-secret", `{"client_task_id":"fail","prompt":"cat"}`)
	if w.Code != 503 || len(blocked.imageTasks) != 0 {
		t.Fatalf("accepted without persistence: %d", w.Code)
	}
}

func TestAsyncImageEditUsesEditHandler(t *testing.T) {
	s := imageTaskTestServer(t)
	task := &imageTaskState{ID: "edit-one", OwnerID: "api", Mode: "edit", Model: "gpt-image-2", N: 1, Prompt: "edit", Images: [][]byte{[]byte("invalid-image")}, Status: "queued"}
	s.runImageTask(context.Background(), task, "Bearer api-secret", "")
	if task.Status != "error" || task.Error != "no available accounts" {
		t.Fatalf("edit did not reach image validation: %+v", task)
	}
	assertImageTaskCallLog(t, s, "edit-one", "failed", "/v1/images/edits")
}

func assertImageTaskCallLog(t *testing.T, s *Server, taskID, status, endpoint string) {
	t.Helper()
	w := imageTaskCall(s, http.MethodGet, "/api/logs?type=call&limit=20", "admin-secret", "")
	if w.Code != http.StatusOK {
		t.Fatalf("logs API: %d %s", w.Code, w.Body.String())
	}
	var result struct {
		Total int              `json:"total"`
		Items []map[string]any `json:"items"`
	}
	if err := json.Unmarshal(w.Body.Bytes(), &result); err != nil {
		t.Fatal(err)
	}
	if result.Total != 1 || len(result.Items) != 1 {
		t.Fatalf("expected one execution log, got %s", w.Body.String())
	}
	row := result.Items[0]
	detail := mapValue(row["detail"])
	shape := mapValue(detail["request_shape"])
	if stringValue(detail["status"]) != status || stringValue(detail["endpoint"]) != endpoint ||
		stringValue(detail["model"]) != "gpt-image-2" || stringValue(shape["client_task_id"]) != taskID ||
		shape["async"] != true || !strings.HasPrefix(stringValue(row["id"]), "image-task-") {
		t.Fatalf("incorrect execution log: %s", w.Body.String())
	}
	outputs, _ := detail["output_images"].([]any)
	if status == "success" && len(outputs) != 1 {
		t.Fatalf("missing generated image in log: %s", w.Body.String())
	}
	if status == "failed" && stringValue(detail["error"]) == "" {
		t.Fatalf("missing error in log: %s", w.Body.String())
	}
	if strings.Contains(w.Body.String(), "api-secret") || strings.Contains(w.Body.String(), "jwt.header.payload") {
		t.Fatal("credentials leaked into the call log")
	}
}

func TestAsyncJSONImageEditValidation(t *testing.T) {
	s := imageTaskTestServer(t)
	t.Setenv("GO_ALLOW_PRIVATE_IMAGE_URLS", "false")
	for _, fields := range []string{
		`"images":[]`, `"images":[""]`, `"images":["data:image/png;base64,!!!"]`,
		`"images":["http://127.0.0.1/a"]`, `"images":["http://169.254.169.254/latest/meta-data"]`,
		`"images":["http://user:password@example.com/a"]`,
		`"n":0,"images":["x"]`, `"n":3,"images":["x"]`, `"n":1.5,"images":["x"]`,
		`"n":9223372036854775808,"images":["x"]`, `"mask":"x","images":["x"]`,
		`"images":["x","x","x","x","x","x","x","x"]`,
	} {
		w := imageTaskCall(s, "POST", "/api/image-tasks/edits", "api-secret", `{"client_task_id":"bad","prompt":"edit",`+fields+`}`)
		if w.Code != 400 {
			t.Errorf("invalid edit accepted: %d", w.Code)
		}
		if strings.Contains(w.Body.String(), "password") {
			t.Error("reference URL leaked")
		}
	}
	if len(s.imageTasks) != 0 {
		t.Fatal("invalid input created tasks")
	}
	w := imageTaskCall(s, "POST", "/api/image-tasks/edits", "wrong-key", `{}`)
	if w.Code != 401 {
		t.Fatalf("unauthorized edit: %d", w.Code)
	}
}

func TestAsyncImageEditMultipartRemainsSupported(t *testing.T) {
	s := imageTaskTestServer(t)
	var body bytes.Buffer
	writer := multipart.NewWriter(&body)
	_ = writer.WriteField("client_task_id", "multipart-edit")
	_ = writer.WriteField("prompt", "edit")
	_ = writer.WriteField("model", "gpt-image-2")
	file, err := writer.CreateFormFile("image[]", "input.png")
	if err != nil {
		t.Fatal(err)
	}
	_, _ = file.Write(tinyPNG)
	_ = writer.Close()
	r := httptest.NewRequest("POST", "/api/image-tasks/edits", &body)
	r.Header.Set("Content-Type", writer.FormDataContentType())
	r.Header.Set("Authorization", "Bearer api-secret")
	w := httptest.NewRecorder()
	s.Handler().ServeHTTP(w, r)
	if w.Code != 202 {
		t.Fatalf("multipart edit: %d %s", w.Code, w.Body.String())
	}
	for deadline := time.Now().Add(3 * time.Second); time.Now().Before(deadline); {
		w = imageTaskCall(s, "GET", "/api/image-tasks/multipart-edit", "api-secret", "")
		if strings.Contains(w.Body.String(), `"status":"error"`) {
			return
		}
		time.Sleep(10 * time.Millisecond)
	}
	t.Fatal("multipart task did not finish")
}

func TestImagePollingDeadlinePreservesUpstreamReason(t *testing.T) {
	s := imageTaskTestServer(t)
	s.cfg.ChatMaxRetries = 2
	s.cfg.ChatRetryCodes = map[int]bool{504: true}
	if _, _, _, err := s.store.AddAccounts(nil, []map[string]any{{"access_token": "jwt.header.payload", "pool": "basic"}}); err != nil {
		t.Fatal(err)
	}
	var starts, polls atomic.Int32
	client := &http.Client{Transport: updateRoundTripFunc(func(r *http.Request) (*http.Response, error) {
		raw := `{}`
		switch r.URL.Path {
		case "/":
			raw = `<html data-build="test"></html>`
		case "/backend-api/sentinel/chat-requirements/prepare":
			raw = `{"prepare_token":"test"}`
		case "/backend-api/sentinel/chat-requirements/finalize":
			raw = `{"token":"test"}`
		case "/backend-api/f/conversation/prepare":
			raw = `{"conduit_token":"test"}`
		case "/backend-api/f/conversation":
			starts.Add(1)
			raw = "data: {\"conversation_id\":\"conversation-timeout\"}\n\ndata: [DONE]\n\n"
		case "/backend-api/conversation/conversation-timeout":
			polls.Add(1)
		default:
			t.Errorf("unexpected path %s", r.URL.Path)
		}
		return &http.Response{StatusCode: 200, Header: make(http.Header), Body: io.NopCloser(strings.NewReader(raw)), Request: r}, nil
	})}
	s.openAIImage = provider.NewOpenAIImage("http://upstream.invalid", client, nil, time.Second)
	ctx, cancel := provider.WithImageTaskTimeout(context.Background(), 100*time.Millisecond)
	defer cancel()
	_, err := s.generateOpenAIImageData(nil, ctx, "test", "gpt-image-2", "1024x1024", "auto", nil, "url", "http://cfm.invalid", 1, provider.ImageOutputOptions{})
	if err == nil || !strings.Contains(err.Error(), "last poll error: upstream response contained no image reference") {
		t.Fatalf("lost polling diagnostic: %v", err)
	}
	if starts.Load() != 1 || polls.Load() != 1 {
		t.Fatalf("unexpected retry: starts=%d polls=%d", starts.Load(), polls.Load())
	}
}
