package httpapi

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"image"
	"image/color"
	"image/png"
	"io"
	"math/rand"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/auucoder/gptgrok2api-go/internal/provider"
)

func TestGPTImageSyncResponseProtocol(t *testing.T) {
	for _, tc := range []struct {
		name, mode string
		n          int
	}{
		{"generations", "generations", 1},
		{"generations-multiple", "generations", 3},
		{"edits-json", "edits-json", 1},
		{"edits-multipart", "edits-multipart", 1},
	} {
		t.Run(tc.name, func(t *testing.T) {
			mode := tc.mode
			s := imageTaskTestServer(t)
			if _, _, _, err := s.store.AddAccounts(nil, []map[string]any{{"access_token": "jwt.header.payload", "pool": "basic"}}); err != nil {
				t.Fatal(err)
			}
			// A non-compressible image makes the Base64 response exceed the
			// monitor's 8 KiB capture cap, reproducing the production regression.
			output := image.NewRGBA(image.Rect(0, 0, 64, 64))
			rng := rand.New(rand.NewSource(1))
			for y := 0; y < 64; y++ {
				for x := 0; x < 64; x++ {
					output.Set(x, y, color.RGBA{R: byte(rng.Intn(256)), G: byte(rng.Intn(256)), B: byte(rng.Intn(256)), A: 255})
				}
			}
			var generated bytes.Buffer
			if err := png.Encode(&generated, output); err != nil {
				t.Fatal(err)
			}
			fileID := "file_000000001234567890abcdef12345678"
			var upstream *httptest.Server
			upstream = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				switch r.URL.Path {
				case "/":
					io.WriteString(w, `<html data-build="test-build"></html>`)
				case "/backend-api/files":
					writeJSON(w, 200, map[string]any{"file_id": "file_reference", "upload_url": upstream.URL + "/upload"})
				case "/upload":
					data, _ := io.ReadAll(r.Body)
					if !bytes.Equal(data, tinyPNG) {
						t.Error("reference changed")
					}
					w.WriteHeader(201)
				case "/backend-api/files/file_reference/uploaded":
					writeJSON(w, 200, map[string]any{"status": "success"})
				case "/backend-api/sentinel/chat-requirements/prepare":
					writeJSON(w, 200, map[string]any{"prepare_token": "test"})
				case "/backend-api/sentinel/chat-requirements/finalize":
					writeJSON(w, 200, map[string]any{"token": "test"})
				case "/backend-api/f/conversation/prepare":
					writeJSON(w, 200, map[string]any{"conduit_token": "test"})
				case "/backend-api/f/conversation":
					w.Header().Set("Content-Type", "text/event-stream")
					io.WriteString(w, `data: {"conversation_id":"conversation-1","message":{"content":{"parts":["file-service://`+fileID+`"]}}}`+"\n\ndata: [DONE]\n\n")
				case "/backend-api/conversation/conversation-1":
					writeHTTPAPIGeneratedImageConversation(w, fileID)
				case "/backend-api/files/" + fileID + "/download":
					writeJSON(w, 200, map[string]any{"download_url": upstream.URL + "/blob"})
				case "/blob":
					w.Header().Set("Content-Type", "image/png")
					w.Write(generated.Bytes())
				default:
					http.NotFound(w, r)
				}
			}))
			defer upstream.Close()
			s.openAIImage = provider.NewOpenAIImage(upstream.URL, upstream.Client(), nil, 30*time.Second)
			var req *http.Request
			if mode == "edits-multipart" {
				var body bytes.Buffer
				writer := multipart.NewWriter(&body)
				writer.WriteField("model", "gpt-image-2")
				writer.WriteField("prompt", "a red cat")
				part, err := writer.CreateFormFile("image[]", "reference.png")
				if err != nil {
					t.Fatal(err)
				}
				part.Write(tinyPNG)
				writer.Close()
				req = httptest.NewRequest("POST", "/v1/images/edits", &body)
				req.Header.Set("Content-Type", writer.FormDataContentType())
			} else {
				body := `{"model":"gpt-image-2","prompt":"a red cat"}`
				path := "/v1/images/generations"
				if tc.n == 3 {
					body = strings.TrimSuffix(body, "}") + `,"n":3}`
				}
				if mode == "edits-json" {
					path = "/v1/images/edits"
					body = strings.TrimSuffix(body, "}") + `,"images":["data:image/png;base64,` + base64.StdEncoding.EncodeToString(tinyPNG) + `"]}`
				}
				req = httptest.NewRequest("POST", path, strings.NewReader(body))
				req.Header.Set("Content-Type", "application/json")
			}
			req.Header.Set("Authorization", "Bearer api-secret")
			w := httptest.NewRecorder()
			s.Handler().ServeHTTP(w, req)
			if w.Code != 200 {
				t.Fatalf("response: %d %s", w.Code, w.Body.String())
			}
			var result struct {
				Created int64               `json:"created"`
				Data    []map[string]string `json:"data"`
				Usage   any                 `json:"usage"`
			}
			if err := json.Unmarshal(w.Body.Bytes(), &result); err != nil {
				t.Fatal(err)
			}
			if result.Created <= 0 || len(result.Data) != tc.n || result.Usage != nil {
				t.Fatal("invalid response metadata")
			}
			if w.Body.Len() <= 8<<10 {
				t.Fatal("fixture must exceed the response capture cap")
			}
			for _, item := range result.Data {
				raw, err := base64.StdEncoding.DecodeString(item["b64_json"])
				if err != nil || !bytes.Equal(raw, generated.Bytes()) || len(item) != 1 {
					t.Fatal("expected only generated Base64 image")
				}
			}
			// Check the persisted log, not the read-time historical repair.
			logs := s.loadCallLogs()
			if len(logs) != 1 {
				t.Fatalf("expected one call log, got %d", len(logs))
			}
			detail := mapValue(logs[0]["detail"])
			outputs := anyList(detail["output_images"])
			if len(outputs) != tc.n || len(anyList(detail["image_urls"])) != tc.n {
				t.Fatalf("generated images missing from persisted log: %#v", detail)
			}
			seen := map[string]bool{}
			for _, value := range outputs {
				url := stringValue(mapValue(value)["url"])
				if !strings.HasPrefix(url, "/images/") || seen[url] {
					t.Fatalf("unexpected or duplicate preview URL: %q", url)
				}
				seen[url] = true
				preview := adminRequest(s.Handler(), "GET", url, nil)
				if preview.Code != 200 || !bytes.Equal(preview.Body.Bytes(), generated.Bytes()) {
					t.Fatal("log preview does not serve the generated image")
				}
			}
			logBytes, err := os.ReadFile(filepath.Join(s.cfg.DataDir, "logs.jsonl"))
			if err != nil || bytes.Contains(logBytes, []byte("b64_json")) || bytes.Contains(logBytes, []byte(result.Data[0]["b64_json"])) {
				t.Fatal("image bytes must not be duplicated into logs")
			}
		})
	}
}

func TestGPTImageRejectsLegacyResponseFormatBeforeGeneration(t *testing.T) {
	for _, mode := range []string{"generations", "edits"} {
		for _, format := range []string{"url", "b64_json", "invalid"} {
			t.Run(mode+"/"+format, func(t *testing.T) {
				s := imageTaskTestServer(t) // No account: validation must precede any upstream attempt.
				body := map[string]any{"model": "gpt-image-2", "prompt": "cat", "response_format": format}
				if mode == "edits" {
					body["images"] = []string{"data:image/png;base64," + base64.StdEncoding.EncodeToString(tinyPNG)}
				}
				raw, _ := json.Marshal(body)
				w := imageTaskCall(s, "POST", "/v1/images/"+mode, "api-secret", string(raw))
				if w.Code != 400 || !strings.Contains(w.Body.String(), `"param":"response_format"`) || !strings.Contains(w.Body.String(), `"type":"invalid_request_error"`) {
					t.Fatalf("response: %d %s", w.Code, w.Body.String())
				}
			})
		}
	}
}
