package httpapi

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"io"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/auucoder/gptgrok2api-go/internal/provider"
)

func maskSourcePNG(t *testing.T) []byte {
	t.Helper()
	im := image.NewNRGBA(image.Rect(0, 0, 2, 2))
	for y := 0; y < 2; y++ {
		for x := 0; x < 2; x++ {
			im.SetNRGBA(x, y, color.NRGBA{R: 200, G: 70, A: 255})
		}
	}
	var b bytes.Buffer
	_ = png.Encode(&b, im)
	return b.Bytes()
}

func testMaskPNG(t *testing.T, right bool, opaque bool) []byte {
	t.Helper()
	cfg, _, err := image.DecodeConfig(bytes.NewReader(maskSourcePNG(t)))
	if err != nil {
		t.Fatal(err)
	}
	im := image.NewNRGBA(image.Rect(0, 0, cfg.Width, cfg.Height))
	for y := 0; y < cfg.Height; y++ {
		for x := 0; x < cfg.Width; x++ {
			a := uint8(255)
			if !opaque && ((x == 0) == !right) {
				a = 0
			}
			im.SetNRGBA(x, y, color.NRGBA{R: 210, G: 70, B: 40, A: a})
		}
	}
	var b bytes.Buffer
	_ = png.Encode(&b, im)
	return b.Bytes()
}
func maskRequest(t *testing.T, path, encoding string, mask any) *http.Request {
	t.Helper()
	var b bytes.Buffer
	contentType := "application/json"
	if encoding == "multipart" {
		writer := multipart.NewWriter(&b)
		_ = writer.WriteField("client_task_id", "mask-test")
		_ = writer.WriteField("model", "gpt-image-2")
		_ = writer.WriteField("prompt", "make the selected object blue")
		part, _ := writer.CreateFormFile("image[]", "source.png")
		_, _ = part.Write(maskSourcePNG(t))
		if raw, ok := mask.([]byte); ok {
			part, _ = writer.CreateFormFile("mask", "mask.png")
			_, _ = part.Write(raw)
		} else if mask != nil {
			_ = writer.WriteField("mask", fmt.Sprint(mask))
		}
		_ = writer.Close()
		contentType = writer.FormDataContentType()
	} else {
		body := map[string]any{"client_task_id": "mask-test", "model": "gpt-image-2", "prompt": "make the selected object blue", "images": []string{"data:image/png;base64," + base64.StdEncoding.EncodeToString(maskSourcePNG(t))}}
		if raw, ok := mask.([]byte); ok {
			body["mask"] = "data:image/png;base64," + base64.StdEncoding.EncodeToString(raw)
		} else if mask != nil {
			body["mask"] = mask
		}
		_ = json.NewEncoder(&b).Encode(body)
	}
	req := httptest.NewRequest("POST", path, &b)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("Authorization", "Bearer api-secret")
	return req
}
func waitMaskTask(t *testing.T, s *Server) {
	t.Helper()
	deadline := time.Now().Add(5 * time.Second)
	for time.Now().Before(deadline) {
		w := imageTaskCall(s, "GET", "/api/image-tasks/mask-test", "api-secret", "")
		var task imageTaskState
		_ = json.Unmarshal(w.Body.Bytes(), &task)
		if task.Status == "success" {
			return
		}
		if task.Status == "error" {
			t.Fatalf("task failed: %s", w.Body.String())
		}
		time.Sleep(10 * time.Millisecond)
	}
	t.Fatal("mask task timed out")
}

func TestImageMaskSyncAsyncNativeProtocol(t *testing.T) {
	for _, path := range []string{"/v1/images/edits", "/api/image-tasks/edits"} {
		for _, encoding := range []string{"json", "multipart"} {
			for _, masked := range []bool{false, true} {
				t.Run(path+"/"+encoding+fmt.Sprint(masked), func(t *testing.T) {
					s := imageTaskTestServer(t)
					_, _, _, err := s.store.AddAccounts(nil, []map[string]any{{"access_token": "jwt.header.payload", "pool": "basic"}})
					if err != nil {
						t.Fatal(err)
					}
					mask := testMaskPNG(t, false, false)
					cfg, _, _ := image.DecodeConfig(bytes.NewReader(maskSourcePNG(t)))
					output := image.NewNRGBA(image.Rect(0, 0, 4, 4))
					output.SetNRGBA(1, 1, color.NRGBA{B: 255, A: 255})
					var generated bytes.Buffer
					_ = png.Encode(&generated, output)
					var calls, maskUploads, sourceUploads atomic.Int32
					fileID := "file_000000001234567890abcdef12345678"
					var upstream *httptest.Server
					upstream = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
						switch r.URL.Path {
						case "/":
							io.WriteString(w, `<html data-build="test-build"></html>`)
						case "/backend-api/files":
							var payload map[string]any
							_ = json.NewDecoder(r.Body).Decode(&payload)
							id := "source"
							if payload["use_case"] == "dalle_agent" {
								id = "mask"
								maskUploads.Add(1)
								if payload["entry_surface"] != "image_edit_mask" || payload["store_in_library"] != false {
									t.Error("mask upload purpose missing")
								}
							} else {
								sourceUploads.Add(1)
								if payload["use_case"] != "multimodal" || payload["entry_surface"] != nil {
									t.Error("source upload changed")
								}
							}
							writeJSON(w, 200, map[string]any{"file_id": "file_" + id, "upload_url": upstream.URL + "/upload/" + id})
						case "/upload/source":
							raw, _ := io.ReadAll(r.Body)
							if !bytes.Equal(raw, maskSourcePNG(t)) {
								t.Error("source bytes changed")
							}
							w.WriteHeader(201)
						case "/upload/mask":
							decoded, err := png.Decode(r.Body)
							if err != nil {
								t.Error(err)
								return
							}
							if decoded.Bounds().Dx() != cfg.Width || decoded.Bounds().Dy() != cfg.Height {
								t.Error("mask dimensions changed")
							}
							v, _, _, a := decoded.At(0, 0).RGBA()
							if v != 0 || a != 65535 {
								t.Error("edit region must be opaque black")
							}
							if cfg.Width > 1 {
								v, _, _, a = decoded.At(1, 0).RGBA()
								if v != 65535 || a != 65535 {
									t.Error("preserved region must be opaque white")
								}
							}
							w.WriteHeader(201)
						case "/backend-api/files/file_source/uploaded", "/backend-api/files/file_mask/uploaded":
							writeJSON(w, 200, map[string]any{"status": "success"})
						case "/backend-api/sentinel/chat-requirements/prepare":
							writeJSON(w, 200, map[string]any{"prepare_token": "test"})
						case "/backend-api/sentinel/chat-requirements/finalize":
							writeJSON(w, 200, map[string]any{"token": "test"})
						case "/backend-api/f/conversation/prepare":
							writeJSON(w, 200, map[string]any{"conduit_token": "test"})
						case "/backend-api/f/conversation":
							calls.Add(1)
							var payload map[string]any
							_ = json.NewDecoder(r.Body).Decode(&payload)
							message := mapValue(anyList(payload["messages"])[0])
							metadata := mapValue(message["metadata"])
							if len(anyList(metadata["attachments"])) != 1 || len(anyList(mapValue(message["content"])["parts"])) != 2 {
								t.Error("mask must not become an ordinary reference image")
							}
							operation := mapValue(mapValue(mapValue(metadata["dalle"])["from_client"])["operation"])
							if masked {
								if operation["type"] != "inpainting" || operation["original_file_id"] != "file_source" || operation["mask_file_id"] != "file_mask" {
									t.Errorf("native operation missing: %#v", operation)
								}
							} else if metadata["dalle"] != nil {
								t.Error("unmasked edit gained mask operation")
							}
							w.Header().Set("Content-Type", "text/event-stream")
							io.WriteString(w, "data: {\"conversation_id\":\"conversation-1\"}\n\ndata: [DONE]\n\n")
						case "/backend-api/conversation/conversation-1":
							writeHTTPAPIGeneratedImageConversation(w, fileID)
						case "/backend-api/files/" + fileID + "/download":
							writeJSON(w, 200, map[string]any{"download_url": upstream.URL + "/blob"})
						case "/blob":
							w.Header().Set("Content-Type", "image/png")
							w.Write(generated.Bytes())
						default:
							http.NotFound(w, r)
						}
					}))
					defer upstream.Close()
					s.openAIImage = provider.NewOpenAIImage(upstream.URL, upstream.Client(), nil, 30*time.Second)
					var maskValue any
					if masked {
						maskValue = mask
					}
					w := httptest.NewRecorder()
					s.Handler().ServeHTTP(w, maskRequest(t, path, encoding, maskValue))
					async := strings.HasPrefix(path, "/api/")
					if async {
						if w.Code != 202 {
							t.Fatalf("accept: %d %s", w.Code, w.Body.String())
						}
						waitMaskTask(t, s)
						// A restart must preserve idempotency without retaining mask/base64 bytes.
						s.imageTaskMu.RLock()
						for _, task := range s.imageTasks {
							if task.Mask != nil {
								t.Error("finished task retained mask")
							}
						}
						s.imageTaskMu.RUnlock()
						entries, _ := os.ReadDir(s.imageTasksDir())
						for _, entry := range entries {
							raw, _ := os.ReadFile(filepath.Join(s.imageTasksDir(), entry.Name()))
							if bytes.Contains(raw, []byte(base64.StdEncoding.EncodeToString(mask))) || bytes.Contains(raw, []byte(`"mask"`)) {
								t.Error("mask leaked into persisted record")
							}
						}
						reloaded := New(s.cfg)
						replay := httptest.NewRecorder()
						reloaded.Handler().ServeHTTP(replay, maskRequest(t, path, encoding, maskValue))
						if replay.Code != 202 || !strings.Contains(replay.Body.String(), `"status":"success"`) {
							t.Fatalf("replay: %d %s", replay.Code, replay.Body.String())
						}
						var other any = mask
						if masked {
							other = nil
						}
						conflict := httptest.NewRecorder()
						reloaded.Handler().ServeHTTP(conflict, maskRequest(t, path, encoding, other))
						if conflict.Code != 409 {
							t.Fatalf("mask presence did not conflict: %d %s", conflict.Code, conflict.Body.String())
						}
						if masked && cfg.Width > 1 {
							conflict = httptest.NewRecorder()
							reloaded.Handler().ServeHTTP(conflict, maskRequest(t, path, encoding, testMaskPNG(t, true, false)))
							if conflict.Code != 409 {
								t.Fatal("different selection did not conflict")
							}
						}
					} else if w.Code != 200 {
						t.Fatalf("sync: %d %s", w.Code, w.Body.String())
					}
					expectedMasks := int32(0)
					if masked {
						expectedMasks = 1
					}
					if calls.Load() != 1 || sourceUploads.Load() != 1 || maskUploads.Load() != expectedMasks {
						t.Fatalf("unexpected upstream counts %d/%d/%d", calls.Load(), sourceUploads.Load(), maskUploads.Load())
					}
				})
			}
		}
	}
}

func TestInvalidMaskRejectedBeforeAcceptance(t *testing.T) {
	for _, path := range []string{"/v1/images/edits", "/api/image-tasks/edits"} {
		for _, encoding := range []string{"json", "multipart"} {
			for _, mask := range []any{[]byte("not png"), testMaskPNG(t, false, true), "", make([]byte, provider.MaxImageMaskBytes+1)} {
				s := imageTaskTestServer(t)
				w := httptest.NewRecorder()
				s.Handler().ServeHTTP(w, maskRequest(t, path, encoding, mask))
				if w.Code != 400 || !strings.Contains(w.Body.String(), `"param":"mask"`) {
					t.Fatalf("%s/%s: %d %s", path, encoding, w.Code, w.Body.String())
				}
				if len(s.imageTasks) != 0 {
					t.Fatal("invalid mask persisted a task")
				}
			}
		}
	}
}

func TestMaskReferenceParsingAndURLProtection(t *testing.T) {
	s := imageTaskTestServer(t)
	mask := testMaskPNG(t, false, false)
	encoded := base64.StdEncoding.EncodeToString(mask)
	for _, value := range []any{encoded, "data:image/png;base64," + encoded, map[string]any{"b64_json": encoded}} {
		got, err := s.imageMaskFromValue(context.Background(), value)
		if err != nil || !bytes.Equal(got, mask) {
			t.Fatalf("valid mask reference: %v", err)
		}
	}
	for _, value := range []any{true, 5, []any{encoded}, map[string]any{}, map[string]any{"file_id": "file_mask"}, map[string]any{"b64_json": encoded, "url": "https://example.test/mask.png"}, "http://127.0.0.1:1/mask.png?secret=sensitive"} {
		t.Setenv("GO_ALLOW_PRIVATE_IMAGE_URLS", "")
		_, err := s.imageMaskFromValue(context.Background(), value)
		if err == nil || strings.Contains(err.Error(), "sensitive") {
			t.Fatalf("unsafe/invalid reference: %v", err)
		}
	}
	if raw, err := s.imageMaskFromValue(context.Background(), nil); err != nil || raw != nil {
		t.Fatal("null must preserve ordinary editing")
	}
}

func TestMaskModelSourceAndDuplicateValidation(t *testing.T) {
	for _, path := range []string{"/v1/images/edits", "/api/image-tasks/edits"} {
		for _, encoding := range []string{"json", "multipart"} {
			for _, scenario := range []string{"unsupported-model", "multiple-sources", "duplicate-mask", "wrong-dimensions"} {
				t.Run(path+encoding+scenario, func(t *testing.T) {
					s := imageTaskTestServer(t)
					mask := testMaskPNG(t, false, false)
					source := maskSourcePNG(t)
					if scenario == "wrong-dimensions" {
						var b bytes.Buffer
						_ = png.Encode(&b, image.NewNRGBA(image.Rect(0, 0, 3, 3)))
						mask = b.Bytes()
					}
					model := "gpt-image-2"
					if scenario == "unsupported-model" {
						model = "grok-imagine-image-edit"
					}
					var b bytes.Buffer
					contentType := "application/json"
					if encoding == "multipart" {
						writer := multipart.NewWriter(&b)
						_ = writer.WriteField("model", model)
						_ = writer.WriteField("prompt", "edit")
						_ = writer.WriteField("client_task_id", "invalid")
						part, _ := writer.CreateFormFile("image[]", "source.png")
						_, _ = part.Write(source)
						if scenario == "multiple-sources" {
							part, _ = writer.CreateFormFile("image", "second.png")
							_, _ = part.Write(source)
						}
						part, _ = writer.CreateFormFile("mask", "mask.png")
						_, _ = part.Write(mask)
						if scenario == "duplicate-mask" {
							part, _ = writer.CreateFormFile("mask[]", "second-mask.png")
							_, _ = part.Write(mask)
						}
						_ = writer.Close()
						contentType = writer.FormDataContentType()
					} else {
						refs := []string{"data:image/png;base64," + base64.StdEncoding.EncodeToString(source)}
						if scenario == "multiple-sources" {
							refs = append(refs, refs[0])
						}
						var value any = "data:image/png;base64," + base64.StdEncoding.EncodeToString(mask)
						if scenario == "duplicate-mask" {
							value = []any{value, value}
						}
						_ = json.NewEncoder(&b).Encode(map[string]any{"model": model, "client_task_id": "invalid", "prompt": "edit", "images": refs, "mask": value})
					}
					req := httptest.NewRequest("POST", path, &b)
					req.Header.Set("Content-Type", contentType)
					req.Header.Set("Authorization", "Bearer api-secret")
					w := httptest.NewRecorder()
					s.Handler().ServeHTTP(w, req)
					if w.Code != 400 || !strings.Contains(w.Body.String(), `"param":"mask"`) {
						t.Fatalf("%d %s", w.Code, w.Body.String())
					}
					if len(s.imageTasks) != 0 {
						t.Fatal("invalid request was accepted")
					}
				})
			}
		}
	}
}

func TestMaskURLBoundedDownloadDoesNotSendCredentials(t *testing.T) {
	t.Setenv("GO_ALLOW_PRIVATE_IMAGE_URLS", "true")
	mask := testMaskPNG(t, false, false)
	remote := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get("Authorization") != "" || r.Header.Get("X-API-Key") != "" {
			t.Error("credential forwarded to mask host")
		}
		w.Header().Set("Content-Type", "image/png")
		if r.URL.Path == "/oversized" {
			_, _ = w.Write(make([]byte, provider.MaxImageMaskBytes+1))
			return
		}
		_, _ = w.Write(mask)
	}))
	defer remote.Close()
	s := imageTaskTestServer(t)
	raw, err := s.imageMaskFromValue(context.Background(), map[string]any{"image_url": remote.URL + "/mask.png"})
	if err != nil || !bytes.Equal(raw, mask) {
		t.Fatalf("URL mask: %v", err)
	}
	if _, err = s.imageMaskFromValue(context.Background(), remote.URL+"/oversized?secret=hidden"); err == nil || strings.Contains(err.Error(), "hidden") {
		t.Fatalf("oversized download: %v", err)
	}
}

func TestInterruptedMaskTaskCannotRegenerateAfterRestart(t *testing.T) {
	s := imageTaskTestServer(t)
	task := &imageTaskState{ID: "mask-test", OwnerID: "owner", Mode: "edit", Status: "running", Model: "gpt-image-2", Size: "auto", SizeVersion: 1, N: 1, Quality: "auto", Prompt: "edit", Images: [][]byte{maskSourcePNG(t)}, Mask: testMaskPNG(t, false, false)}
	task.RequestHash = imageTaskHash(task)
	if err := s.saveImageTaskLocked(task); err != nil {
		t.Fatal(err)
	}
	restored := New(s.cfg)
	got := restored.imageTasks[imageTaskKey(task.OwnerID, task.ID)]
	if got == nil || got.Status != "error" || got.RequestHash != task.RequestHash || got.Mask != nil || got.Images != nil {
		t.Fatalf("invalid restart state: %#v", got)
	}
	// Directly replaying the same owner-scoped request returns its interruption,
	// without an account or upstream request being necessary.
	req := httptest.NewRequest("POST", "/api/image-tasks/edits", nil)
	w := httptest.NewRecorder()
	restored.submitImageTask(w, req, task)
	if w.Code != 202 || !strings.Contains(w.Body.String(), `"status":"error"`) {
		t.Fatalf("interrupted replay: %d %s", w.Code, w.Body.String())
	}
}
